name: CI_CD_Terraform_Apply (caller)

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Target environment"
        required: true
        default: "Production"
      WORKING_FOLDER:
        description: "Terraform working directory"
        required: true
        default: "infra"

jobs:
  terraform-apply:
    # 👇 REQUIRED, or else you'll get "runs-on missing"
    uses: ./.github/workflows/ci-cd-terraform-reusable.yml
    with:
      environment: ${{ github.event.inputs.ENVIRONMENT }}
      working-directory: ${{ github.event.inputs.WORKING_FOLDER }}
      apply: true
