name: reusable-terraform

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      terraform_version:
        required: false
        type: string
        default: "1.6.6"

jobs:
  fmt-validate-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform FMT (check only)
        working-directory: ${{ inputs.working_directory }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ inputs.working_directory }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ inputs.working_directory }}
        run: |
          set -e
          terraform plan -input=false -out=tfplan.out
          terraform show -no-color tfplan.out > tfplan.txt

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            ${{ inputs.working_directory }}/tfplan.out
            ${{ inputs.working_directory }}/tfplan.txt
