on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      terraform_version:
        required: true
        type: string
      apply:
        required: false
        default: false
        type: boolean

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        working-directory: ${{ inputs.working_directory }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ inputs.working_directory }}
        run: terraform validate

      - name: Terraform Plan
        if: ${{ inputs.apply == 'false' }}
        working-directory: ${{ inputs.working_directory }}
        run: terraform plan -out=tfplan

      - name: Upload Plan
        if: ${{ inputs.apply == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ inputs.working_directory }}/tfplan

      - name: Terraform Apply
        if: ${{ inputs.apply == 'true' }}
        working-directory: ${{ inputs.working_directory }}
        run: terraform apply -auto-approve
